### ISSUE TITLE
通过reposync方式进行代码同步一直都运行失败

### ISSUE THREAD

**Issue by mychen1** [Naughty-Monkey/JdActions#1]
代码这样，同步时候都是一直失败，想请问下怎么弄好点
![360截图18720122105149123](https://user-images.githubusercontent.com/77484173/104708013-1f5f2600-5758-11eb-86af-906528ac8d90.jpg)
![360截图18720123408753](https://user-images.githubusercontent.com/77484173/104708030-2423da00-5758-11eb-98a6-179c2509d5d0.jpg)

**Comment by mychen1** [comment]
# File: .github/workflows/repo-sync.yml
name: sync-Naughty-Monkey-scripts
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-sazs34-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ github.event.client_payload.PAT || secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Naughty-Monkey-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Naughty-Monkey/JdActions.git"
          source_branch: "master"
          destination_branch: "main"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}

**Comment by Naughty-Monkey** [comment]
为了支持大佬，防止大佬账户再次被封，故以后不再使用action运行脚本，希望你可以删除仓库
